apiVersion: v1
kind: Service
metadata:
  labels:
    role: db
  name: db-headless
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  clusterIP: None
  selector:
    name: db