apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: rmq
  name: rmq
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rmq
  template:
    metadata:
      labels:
        name: rmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: rmqcreds
                key: user
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: rmqcreds
                key: pass