apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dbcreds
  namespace: default
spec:
  encryptedData:
    pass: AgBD0DsBjSOl3UcsVFTr9ZSgqUMnobdGt4fT+fIoM6sTUZNRPuBcquClBaTlRuYPNBU6oyPDKbv4sOOe7Q/fRL1WT9rH1kyBLWFtXONoEYyF78/jqnVuWhEYS1hD7Jiws2jTZzOs0ssymYexR4Ey/ax96U/QtRl2r5uvaPhjdtzhtadkOJpx2OTonT/jagpNDqDldpZiuK1ZrJtEEYQhCkvmXSKZL9+Yog/6Sp4lVYcXbZ5T4P9YbmYdM104KLxSI5nU8fUokP8Pd1ywdzH5KPesOuY5fQVoqI9yaig80rMYP7VHmphG5Pb7XSDEh+1HSys0z6LyAlPTlfE1RwtzNbzFlqw+csEoKOLgfi0bu6SMjLUNOAmHf2k4cswCKbXoBXG1++rrFffeyYnZ2G1/xSsO264xTbndqpHirftkHF6xfKJsKQHvt27W3o+6D5CUAbxXjTSczCfoOD9qRZJi2uIUmbJc5RnU6MjaZWybCCk7eqJ6AAFbR2zsk5hz5z2hBynTxOUJUKfRIvC3oT60o8ppE3eMLnCr/HU64aT3mYIEO8Ty2k51fYE6Tx/1V122Ejfhy22YVd5Cs0oyef/O5nH8+oYqSFsEjF6OaALarDec3GaoqqpU6Zb1aIij7ZBNWJxkmWQOCAWVqy8NbdmxMGzIUfa6jXF05wzOpSCFAewLIR6AM64au9oX8x+OAitHW5C3+8Yk
    user: AgB5wxxdAU3usDYf61ZbFrqVn6oQ1RqGefoUA+9mcL451l4J+WIaF/QAVSEixCPI3tEr5EtYvGAlqrcE0/GvD0LdfYT9U6fMK8LFNAwPP1NqHC6+qAfbNlCwVnO/1aLVK/mwf654dRmktNEDca6nNCS0EqKe2TwmrzPMJZ1beCVw34bjYja/6AL61FB2uybYB4Othmc0HCO/+7nLJQRQutIOb+vbBGznELtBAt1j8umB9Z/Gn3RkpHTImO2U3nLbk1daw8HvIZLiqLMPbfzvV756OzddCIGZ6Qr7+sNIqLNfT62/6GImV19X+EK466KxtcQwsdk+O/6TJZg8p5/Bs2pefWNWv7NX9n0wzZLUGTz1Vcl4NsyHP/+9Gieg5+Ic94gbKGBfIDvoBr7rpTm743L09zr+IlMGElPS3oJAE/yYzuJ77ptVcz0ORgihrttUYOvvcC/T5TpN2jgUafjEZibrm/JqyylRkGTcvziL3yZO07xZhtgoEPvKK7g8dO3uisMz+cgT5JZdBT18CfUfh33fq/4oaeXSACm0cMFPAVS4nRiHaOR3q29DBzfhlwSR1IkVVPHSzIKR5hWL/8d3BiT6AusvHZUn5uzgSZn+eCkPXHfdRJdLT9QZvtf1oMV6fpSJDUnQ84cj5BmVd3yJauRgq+K7pRvp9FN+KqnNFDS4tMhAF7NKYkL+a0JABLpetV3QSZag
  template:
    metadata:
      creationTimestamp: null
      name: dbcreds
      namespace: default